### PR TITLE
Fix columns on dashboard index

### PR DESCRIPTION
**Pull request by lukasedw**

### CODE REVIEW

**Comment by dkniffin** [comment]
@lukasedw Would you mind describing the issue this fixes? A screenshot would be great too, since it's a CSS change.

**Comment by DaniTheLion** [comment]
Hi @dkniffin I'm not the author of the PR but I've found it while searching for a solution to this issue. The issue is that columns on the dashboard page are stacked horizontally rather than being displayed side by side. 

The following dashboard definition
```ruby
ActiveAdmin.register_page "Dashboard" do
  menu priority: 1, label: proc { I18n.t("active_admin.dashboard") }

  content title: proc { I18n.t("active_admin.dashboard") } do
    columns do
      column do
        span "Column # 1"
      end
      column do
        span "Column # 2"
      end
    end
  end
end
```

yields this result: 

Screen Shot 2021-03-12 at 22 05 43


I can confirm that adding the change it solves the issues and yields the following result: 

Screen Shot 2021-03-12 at 22 08 30

My css skills are rather limited so I can't really speak of the approach in this PR but a conceptual +1 from me to see this fixed 😄 🙏

**Comment by DaniTheLion** [comment]
Hi @dkniffin I'm not the author of the PR but I've found it while searching for a solution to this issue. The issue is that columns on the dashboard page are stacked horizontally rather than being displayed side by side. 

 The following dashboard definition
 ```ruby
 ActiveAdmin.register_page "Dashboard" do
   menu priority: 1, label: proc { I18n.t("active_admin.dashboard") }

   content title: proc { I18n.t("active_admin.dashboard") } do
     columns do
       column do
         span "Column # 1"
       end
       column do
         span "Column # 2"
       end
     end
   end
 end
 ```

 yields this result: 

Screen Shot 2021-03-12 at 22 20 40


I can confirm that adding the change it solves the issues and yields the following result: 

Screen Shot 2021-03-12 at 22 21 13

 My css skills are rather limited so I can't really speak of the approach in this PR but a conceptual +1 from me to see this fixed 😄 🙏

**Review by dkniffin — APPROVED** [review]
Looks good to me. 👍

**Pull request merged**
